### ISSUE TITLE
Internal server error 500 after update to v1.7.7 - WC_Facebookcommerce_Pixel' not found

### ISSUE THREAD

**Issue by sm7uge** [facebookincubator/facebook-for-woocommerce#235]
I had a notice that the plugin had an update to v1.7.7. After update, both backend and frontend ended up with error 500. Had to go in by ftp and rename the plugin folder to get going again.

Installed versione 1.7.5 and it worked again.

Error message in the log:

2018-01-26T09:38:16+00:00 CRITICAL Uncaught Error: Class 'WC_Facebookcommerce_Pixel' not found in /customers/5/b/e/DOMAIN.se/httpd.www/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:39
Stack trace:
#0 /customers/5/b/e/DOMAIN.se/httpd.www/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(88): WC_Facebookcommerce_Integration->init_settings()
#1 /customers/5/b/e/DOMAIN.se/httpd.www/wp-content/plugins/woocommerce/includes/class-wc-integrations.php(39): WC_Facebookcommerce_Integration->__construct()
#2 /customers/5/b/e/DOMAIN.se/httpd.www/wp-content/plugins/woocommerce/includes/class-woocommerce.php(443): WC_Integrations->__construct()
#3 /customers/5/b/e/DOMAIN.se/httpd.www/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#4 /customers/5/b/e/DOMAIN.se/httpd.www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /customers/5/b/e/DOMAIN.se/httpd.www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /customers/5/b/e/DOMAIN.se/httpd.www/wp-settings.php(450): do

**Comment by dmitridr** [comment]
Ouch. We're going to ship 1.7.8 to fix this in a few hours, thanks for flagging this!

**Comment by Cristist** [comment]
I suggest you test the plugin with PixelYourSite activated: https://wordpress.org/plugins/pixelyoursite/

When both are activated, v1.7.7 generates indeed this error: Uncaught Error: Class 'WC_Facebookcommerce_Pixel' not found in ..../wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:39

All it's fine in previous versions.

**Comment by dmitridr** [comment]
Thank you for reporting this to us so quickly.

[1.7.8](https://github.com/facebookincubator/facebook-for-woocommerce/releases) is out and fixes this issue. @jlkalberer confirmed it fixes the problem for PixelYourSite as well. Strange that we did not catch this in our own initial testing.

**Comment by DjMorgul** [comment]
Hello, after updating to 1.7.8, it's crashing to me again with the following error message:

[26-Jan-2018 20:34:18 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Facebookcommerce_EventsTracker::__construct(), 1 passed in /home/eldesper/public_html/alquimiasubliminal.com/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 272 and exactly 2 expected in /home/eldesper/public_html/alquimiasubliminal.com/wp-content/plugins/pixelyoursite/inc/integrations/facebook-for-woocommerce.php:24
Stack trace:
#0 /home/eldesper/public_html/alquimiasubliminal.com/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(272): WC_Facebookcommerce_EventsTracker->__construct(Array)
#1 /home/eldesper/public_html/alquimiasubliminal.com/wp-content/plugins/woocommerce/includes/class-wc-integrations.php(39): WC_Facebookcommerce_Integration->__construct()
#2 /home/eldesper/public_html/alquimiasubliminal.com/wp-content/plugins/woocommerce/includes/class-woocommerce.php(443): WC_Integrations->__construct()
#3 /home/eldesper/public_html/alquimiasubliminal.com/wp-includes/class-wp-hook.php(286): WooCommerce-> in /home/eldesper/public_html/alquimiasubliminal.com/wp-content/plugins/pixelyoursite/inc/integrations/facebook-for-woocommerce.php on line 24

**Comment by sm7uge** [comment]
Thanks guys!  Great job fixing this so fast!  I'll try installing the new version tomorrow.

**Comment by Cristist** [comment]
Hey guys, your plugin and PixelYourSite share quite a large number of common users. 
Since some of our users asked to be able to manage their pixel with our plugin but still have a Facebook Shop, we made it possible for them. 

It would in their interest if you test against our plugins before your release something that might affect this integration. As far as I understand, your v1.7.7 caused a fatal crash. It appears that v1.7.8 still has some issues. Maybe you can take a look into this and fix them.

Everything was fine before these releases.

You contact me on our site and I can send you a pro version, so you can test it with your major releases in the feature: http://www.pixelyoursite.com/contact
